server {
    listen 80;
    server_name pharmaprices.shop api.pharmaprices.shop;

    root /var/www/public;

    location /.well-known/acme-challenge/ {
        allow all;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}
